name: "Subtitle Extract"
guid: "CD893C24-B59E-4060-87B2-184070E1BF68"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-subtitleextract.png"
version: 3
targetAbi: "10.8.10.0"
framework: "net6.0"
owner: "jellyfin"
overview: "Extracts Subtitles."
description: >
  Extracts embedded subtitles.

category: "General"
artifacts:
  - "Jellyfin.Plugin.SubtitleExtract.dll"
changelog: |2-
  ### New features and improvements ###
  - Allow for subtitles to be extracted for new media (#14) @Kakoluz
